- hosts: nfs_clients

  tasks:
    - name: Ensure NFS common is installed.
      apt: name=nfs-common state=installed update_cache=yes
    - name: Ensure cifs-utils is installed.
      apt: name=cifs-utils state=installed update_cache=yes