apiVersion: v1
kind: Pod
metadata:
  name: registry
  labels:
    app: registry
  namespace: docker-registry
spec:
  volumes:
  - name: registry-data
    persistentVolumeClaim:
      claimName: registry-data

  containers:
  - name: registry
    image: registry:2
    imagePullPolicy: Always
    ports:
    - containerPort: 5000
    volumeMounts:
    - mountPath: /var/lib/registry
      name: registry-data

---
kind: Service
apiVersion: v1
metadata:
  name: registry
  namespace: docker-registry

spec:
  type: NodePort
  selector:
    app: registry
  ports:
  - targetPort: 5000
    port: 5000
    nodePort: 30100