controller:
  nodeSelector:
    node-role.kubernetes.io/master: ""

  tolerations:
    - key: "key"
      operator: "Equal"
      value: "master"
      effect: "NoSchedule"

  service:
    externalIPs:
      - x.x.x.x